export const ERROR_CODES = new Map([
    [201, 'Country code invalid.'],
    [202, 'Recipient number invalid.'],
    [300, 'Authentication missing.'],
    [301, 'Parameter to missing.'],
    [304, 'Parameter type missing.'],
    [305, 'Parameter text missing.'],
    [306, 'Sender invalid.'],
    [307, 'Parameter url missing.'],
    [400, 'Invalid type.'],
    [401, 'Parameter text too long.'],
    [402, 'Reload lock.'],
    [500, 'Not enough credits.'],
    [600, 'Carrier failed.'],
    [700, 'Unknown error.'],
    [801, 'Logo file missing.'],
    [802, 'Logo file not existent.'],
    [803, 'Ring tone missing.'],
    [900, 'Wrong API key!'],
    [901, 'Wrong message ID.'],
    [902, 'API deactivated.'],
    [903, 'IP not allowed.'],
]);